//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agric.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Essai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Essai()
        {
            this.Notation = new HashSet<Notation>();
        }

        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        [Display(Name = "Code_Client")]
        public string CodeClient { get; set; }
        [Display(Name = "Type d'application")]
        public string TA { get; set; }
        public string Formulation { get; set; }
        [Display(Name = "Dose de Produit")]
        public string DP { get; set; }
        [Display(Name = "Matière Active")]
        public string MA { get; set; }
        public string DateNotation { get; set; }
        [Display(Name = "Protocole Expérimental")]
        public string PE { get; set; }
        [Display(Name = "Date Réception Produit")]
        public string Usage { get; set; }
        [Display(Name = "Produit Réf")]
        public string PR { get; set; }
        [Required(ErrorMessage = "Veuillez ajouter le produit")]
        public string Produit { get; set; }
        [Required(ErrorMessage = "Veuillez ajouter le culture")]
        public string Culture { get; set; }
        [Required(ErrorMessage = "Veuillez ajouter la cible")]
        public string Cible { get; set; }
        [Display(Name = "Date Réception ACB")]
        public string Nb { get; set; }
        public string Region { get; set; }
        [Display(Name = "Code Essai")]
        public string Code { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Date_Cloture { get; set; }
        public string Rapport { get; set; }
        [Display(Name = "Rapport Remis")]
        public Nullable<bool> RapportRemis { get; set; }
        [Display(Name = "Date de Remise du Rapport")]
        public Nullable<System.DateTime> DateRemisRapport { get; set; }
        public string ACB { get; set; }
        public string FDS { get; set; }
        [Display(Name = "Nom de Tech-Labo")]
        public string LaboName { get; set; }
        [Display(Name = "Nom de Tech-Exp")]
        public string TechName { get; set; }
        [Display(Name = "Date d'installation")]
        public string TE { get; set; }
        [Display(Name = "Fiche de Notation")]
        public string FNNotation { get; set; }
        [Display(Name = "Fiche de données d'essai")]
        public string FDEFicheEssai { get; set; }
        public bool EssaiDelets { get; set; }
        [Display(Name = "Dose du Produit Réf")]
        public string DPRéf { get; set; }
        [Display(Name = "Formulation du produit réf")]
        public string FormulationProduitRéf { get; set; }
        [Display(Name = "Mode d'action ")]
        public string Devis { get; set; }
        [Display(Name = "Etat d'essai")]
        public string EtatEssai { get; set; }
        public bool DevisDemander { get; set; }
        [Display(Name = "Etat de Mesure")]
        public Nullable<bool> EtatPaiment { get; set; }
        public Nullable<bool> Paiment_Regler100 { get; set; }
        [Display(Name = "Paiement  ")]
        public Nullable<bool> Paiment_Regler50 { get; set; }
        public bool Payer { get; set; }
        public bool NonPayer { get; set; }
        public bool Payer50 { get; set; }
        public string Facture { get; set; }
        [Display(Name = "Matière active réf ")]
        public string MARéf { get; set; }
        public Nullable<System.DateTime> Date_Modife { get; set; }
        public Nullable<System.Guid> id_devis { get; set; }
        public int Numdevie { get; set; }
        public int nbr { get; set; }
        [Display(Name = "Epoque d'application ")]
        public string ComportementCulture { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Date_Instalation { get; set; }

        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notation> Notation { get; set; }
    }
}
