//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agric.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public System.Guid Id { get; set; }
        public string Operation { get; set; }
        public System.DateTime Date_Modification { get; set; }
        public Nullable<System.Guid> Id_User { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> Id_Essai { get; set; }
        public bool VuAdmin { get; set; }
        public bool VuClient { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
