//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agric.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Notation
    {
        public System.Guid Id { get; set; }
        [Display(Name = "date prévisionnelle")]
        public System.DateTime D_N_P { get; set; }
        [Display(Name = "Date réelle")]
        public Nullable<System.DateTime> D_N_R { get; set; }
        [Display(Name = "Fiche de notation")]
        public string FNotation { get; set; }
        public System.Guid Essai_Id { get; set; }
        [Display(Name = "Date d'ajoute")]
        public Nullable<System.DateTime> Date_Add { get; set; }

        public virtual Essai Essai { get; set; }
    }
}
